### ISSUE TITLE
help request

### ISSUE THREAD

**Issue by NeonLightning** [mpapis/home_dotfiles#3]
was wondering if you'd be able to help me write up something to switch to a bluetooth audio input source and set hdmi out as the output sink? i got it using the pavcontrol but i'm looking to make it automated and not require any mouse or keyboard input at all in the end. even if it's just disabling all else.

**Comment by NeonLightning** [comment]
sorry just saw how old your pulseaudio script is i'm doubting you'd wanna touch it again.

**Comment by mpapis** [comment]
hey, indeed I would need to spend time to learn it again, feel free to use it as help in building your own solution
